import Head from "next/head";
import Image from "next/image";

import React, { useState } from "react";
import { GetServerSideProps } from "next";
import { NextPageWithLayout } from "./_app";
import AppLayout from "@/appLayout";

export const getServerSideProps: GetServerSideProps = async () => {
  const result = (await fetch("http://localhost:5000/api/posts").then((res) =>
    res.json()
  )) as { data: string[] };

  return {
    props: {
      data: result.data,
    },
  };
};

const SecondSection: React.FC<{ data: string[] }> = ({ data }) => {
  const [postData, setPostData] = useState(data);
  return (
    <section className="flex-auto flex flex-col gap-y-6">
      {postData.map((item, index) => (
        <div
          key={index}
          className=" p-6 flex flex-col gap-y-4 border rounded-2xl shadow-sm"
        >
          <div className="flex gap-x-4">
            <div className=" w-12 h-12 rounded-full overflow-hidden">
              <Image
                alt="profile pic"
                width={48}
                height={48}
                src={
                  "https://cdna.artstation.com/p/assets/images/images/008/900/210/large/ina-wong-sindragosacrop1.jpg?1515997173"
                }
              />
            </div>
            <div>
              <p className="font-medium">Aung Moe Oo</p>
              <p className="text-xs text-[#A5A5A5]">TaukToMaYa at MyWork</p>
            </div>
          </div>
          <div className="font-medium">{item}</div>
          <div className="flex gap-x-20">
            <button className="font-medium">Like</button>
            <button className="font-medium">comment</button>
            <button className="font-medium">report</button>
          </div>
        </div>
      ))}
      <div
        className="font-bold text-2xl text-center py-4 mb-6"
        onClick={() => setPostData((current) => [...current, "Another One!"])}
      >
        No More!
      </div>
    </section>
  );
};

const MemoSecondSection = React.memo(({ data }: { data: string[] }) => (
  <SecondSection data={data} />
));

const Home: NextPageWithLayout<{ data: string[] }> = ({ data }) => {
  return (
    <>
      <Head>
        <title>WebForum</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MemoSecondSection data={data} />
    </>
  );
};

export default Home;

Home.getLayout = function getLayout(page: React.ReactElement) {
  return <AppLayout>{page}</AppLayout>;
};
